// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMfVncXebM9bUhIaoYjFJpeIo4T8Hdlw',
    appId: '1:437376103269:web:4825a67e036b72a1f0278c',
    messagingSenderId: '437376103269',
    projectId: 'todoapp-e2e56',
    authDomain: 'todoapp-e2e56.firebaseapp.com',
    storageBucket: 'todoapp-e2e56.firebasestorage.app',
    measurementId: 'G-0NLCWWXXYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpEeRKkM57NEJJ2fs4wr3mtN34uczI-Uc',
    appId: '1:437376103269:android:cf8da040e2d728e4f0278c',
    messagingSenderId: '437376103269',
    projectId: 'todoapp-e2e56',
    storageBucket: 'todoapp-e2e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHbw046hFhrUCyoLNxzz2gqrXf1HDcPuk',
    appId: '1:437376103269:ios:eefe75e265dcf905f0278c',
    messagingSenderId: '437376103269',
    projectId: 'todoapp-e2e56',
    storageBucket: 'todoapp-e2e56.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHbw046hFhrUCyoLNxzz2gqrXf1HDcPuk',
    appId: '1:437376103269:ios:eefe75e265dcf905f0278c',
    messagingSenderId: '437376103269',
    projectId: 'todoapp-e2e56',
    storageBucket: 'todoapp-e2e56.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMfVncXebM9bUhIaoYjFJpeIo4T8Hdlw',
    appId: '1:437376103269:web:56de07edce2d852bf0278c',
    messagingSenderId: '437376103269',
    projectId: 'todoapp-e2e56',
    authDomain: 'todoapp-e2e56.firebaseapp.com',
    storageBucket: 'todoapp-e2e56.firebasestorage.app',
    measurementId: 'G-4V2RXJCQ2R',
  );
}
